language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
before_install:
  - npm install -g codecov lerna
install:
  - lerna exec npm install
script:
  - lerna exec npm run test:unit --scope @parcel-vue-ts/template
  - lerna exec npm run build --scope @parcel-vue-ts/template
after_success:
  - lerna exec codecov --scope @parcel-vue-ts/template
# deploy:
#   local_dir: packages/template/build
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   on:
#     branch: master
branches:
  only:
    - master
