language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules # NPM packages
before_script:
  - npm install
script:
  - npm run build
deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
branches:
  only:
    - master
